apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: dknova-app-monitor
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dknova-app

  endpoints:
  - port: http
    path: /metrics
    interval: 15s
